VerifikatorPendapatan/Controllers/PostingKeuanganController.cs
using VerifikatorPendapatan.Entities.SIM;
using VerifikatorPendapatan.Helper;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using VerifikatorPendapatan.Models;
using System.Data.Entity.Validation;

namespace VerifikatorPendapatan.Controllers
{
    public class PostingKeuanganController : Controller
    {
        #region === POSTING KE KEUANGAN
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string ListPosting(string FromDate, string ToDate, bool AllPeriode, string search, string TipePasien)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.AU_ListPosting.AsQueryable();
                    if (AllPeriode == false)
                    {
                        if (!string.IsNullOrEmpty(FromDate))
                        {
                            var fDate = DateTime.Parse(FromDate);
                            proses = proses.Where(y => y.TglClosing >= fDate);
                        }
                        
                        
                        if (!string.IsNullOrEmpty(ToDate))
                        {
                            var tDate = DateTime.Parse(ToDate);
                            proses = proses.Where(y => y.TglClosing <= tDate);
                        }
                        
                    }

                    if (search != null && search != "")
                    {
                        proses = proses.Where(y =>
                                                y.NoBukti == search ||
                                                y.NoInvoice == search ||
                                                y.NamaPasien == search
                                            );
                    }

                    if (TipePasien != null && TipePasien != "")
                    {
                        if (TipePasien != "ALL")
                        {
                            proses = proses.Where(y =>
                                                y.JenisKerjasama == TipePasien
                                            );
                        }
                    }

                    totalcount = proses.Count();
                    var models = proses.ToList();
                    var r = models.ConvertAll(x => new
                    {
                        NoBukti = x.NoBukti,
                        TglAudit = x.TglAudit.ToString("dd/MM/yyyy"),
                        NoInvoice = x.NoInvoice,
                        TglClosing = x.TglClosing.Value.ToString("dd/MM/yyyy"),
                        NamaPasien = x.NamaPasien,
                        Keterangan = x.Keterangan,
                        JenisKerjasama = x.JenisKerjasama
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        [ActionName("Create")]
        public string Create_post()
        {
            var item = new PostingKeuanganViewModel();
            TryUpdateModel(item);
            try
            {
                using (var s = new SIMEntities())
                {
                    using (var dbContextTransaction = s.Database.BeginTransaction())
                    {
                        var dt = "";
                        var error = 0;
                        var succes = 0;
                        foreach (var x in item.detail)
                        {
                            var d = new
                            {
                                NoBukti = x.NoBukti,
                                Posting = x.Posting,
                            };
                            if (d.Posting == true)
                            {
                                dt = s.Verif_Posting(d.NoBukti).FirstOrDefault();
                            }
                            if (dt == d.NoBukti)
                            {
                                succes += 1;
                            }
                            else
                            {
                                error += 1;
                            }
                        }
                        dbContextTransaction.Commit();

                        return JsonConvert.SerializeObject(new 
                        { 
                            IsSuccess = true, 
                            Message = "Data berhasil diposting",
                            DataError = error,
                            DataSuccess = succes
                        });
                    }
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }
        #endregion

        #region === CANCEL POSTING KE KEUANGAN
        [HttpGet]
        public ActionResult Cancel()
        {
            return View();
        }
        
        [HttpPost]
        [ActionName("Cancel")]
        public string Cancel_post()
        {
            var item = new PostingKeuanganViewModel();
            TryUpdateModel(item);
            try
            {
                using (var s = new SIMEntities())
                {
                    using (var dbContextTransaction = s.Database.BeginTransaction())
                    {
                        var dt = "";
                        var error = 0;
                        var succes = 0;
                        foreach (var x in item.detail)
                        {
                            var d = new
                            {
                                NoBukti = x.NoBukti,
                                Posting = x.Posting,
                            };
                            if (d.Posting == true)
                            {
                                dt = s.Verif_Posting_Cancel(d.NoBukti).FirstOrDefault();
                            }
                            if (dt == d.NoBukti)
                            {
                                succes += 1;
                            }
                            else
                            {
                                error += 1;
                            }
                        }
                        dbContextTransaction.Commit();

                        return JsonConvert.SerializeObject(new
                        {
                            IsSuccess = true,
                            Message = "Data berhasil diposting",
                            DataError = error,
                            DataSuccess = succes
                        });
                    }
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string ListCancelPosting(string FromDate, string ToDate, bool AllPeriode, string search)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.AU_ListCancelPosting.AsQueryable();
                    if (AllPeriode == false)
                    {
                        if (!string.IsNullOrEmpty(FromDate))
                        {
                            var fDate = DateTime.Parse(FromDate);
                            proses = proses.Where(y => y.TglClosing >= fDate);
                        }


                        if (!string.IsNullOrEmpty(ToDate))
                        {
                            var tDate = DateTime.Parse(ToDate);
                            proses = proses.Where(y => y.TglClosing <= tDate);
                        }

                    }

                    if (search != null && search != "")
                    {
                        proses = proses.Where(y =>
                                                y.NoBukti == search ||
                                                y.NoInvoice == search ||
                                                y.NamaPasien == search
                                            );
                    }

                    totalcount = proses.Count();
                    var models = proses.ToList();
                    var r = models.ConvertAll(x => new
                    {
                        NoBukti = x.NoBukti,
                        TglAudit = x.TglAudit.ToString("dd/MM/yyyy"),
                        NoInvoice = x.NoInvoice,
                        TglClosing = x.TglClosing.Value.ToString("dd/MM/yyyy"),
                        NamaPasien = x.NamaPasien,
                        Keterangan = x.Keterangan
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }
        #endregion
    }
}

VerifikatorPendapatan/Views/Shared/_Footer.cshtml
<div id="loading" class="hide">
    <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>

<script>
        document.addEventListener("DOMContentLoaded", function (event) {
            initmahas();
            @if (ViewBag.Title != "Home")
        {
            @:$('#menu-toggle-xs').click();
        }
            
        });
</script>

VerifikatorPendapatan/Views/Shared/_Header.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="~/Themes/images/logo.png" type="image/x-icon">
<title>@ViewBag.Title - @VerifikatorPendapatan.Helper.ConfigModel.AppName</title>


<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="~/Themes/assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/colors.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/components.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/core.min.css" rel="stylesheet" />
<link href="~/Themes/assets/css/icons/icomoon/styles.css" rel="stylesheet" />
<link href="~/Themes/assets/css/icons/fontawesome/styles.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

<script src="~/Themes/assets/js/core/libraries/jquery.min.js"></script>
<script src="~/Themes/assets/js/core/libraries/bootstrap.min.js"></script>
<script src="~/Themes/assets/js/core/app.min.js"></script>
<script src="~/Themes/assets/js/plugins/forms/selects/select2.min.js"></script>
<script src="~/Themes/assets/js/plugins/cleave.min.js"></script>
<script src="~/Themes/assets/js/plugins/notifications/pnotify.min.js"></script>

<script src="~/Scripts/mahas.js"></script>
<script>
    function alertpopup(text, status) {
        var newText = '';
        text = text || 'danger';
        if (status === 'danger') {
            if (text.length > 1000) text = 'Internal Server Error';
        }
        $.each(text.split("|"), function (index, value) {
            newText += "<li>" + value + "</li>";
        });
        var icon = status === 'success' ? 'icon-checkmark3' :
            status === 'danger' ? 'icon-blocked' :
                status === 'info' ? 'icon-info22' :
                    status === 'warning' ? 'icon-warning22' :
                        '';
        var myStack = { "dir1": "down", "dir2": "right", "push": "top" };
        new PNotify({
            title: status,
            icon: icon,
            text: newText,
            type: status,
            stack: myStack
        });
    }
</script>
<style>
    .app-name {
        font-size: 18px;
        font-weight: bolder;
        letter-spacing: 3px;
        text-align: center;
    }

    .navbar-brand {
        width: 100%;
        padding: 13px;
    }
</style>

VerifikatorPendapatan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Header")
    <style>
        .navbar-header {
            min-width: 140px;
        }
        .form-group{
            margin-bottom:10px;
        }
    </style>
</head>

@{
    var sidebar = Request.Cookies["sidebar"] == null ? false : bool.Parse(Request.Cookies["sidebar"].Value);
}

<body>
    <div class="navbar navbar-inverse">

        <div class="navbar-header">
            <a class="navbar-brand text-center" href="@Url.Action("Index","Home")">
                <span class="app-name">VERIF PENDAPATAN</span>
            </a>
            <ul class="nav navbar-nav visible-xs-block">
                <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
                <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
            </ul>
        </div>

        <div class="navbar-collapse collapse" id="navbar-mobile">
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="nav navbar-nav">
                    <li><a id="menu-toggle-xs" class="sidebar-control sidebar-main-toggle hidden-xs" onclick="sidebartoggleclick()"><i class="icon-paragraph-justify3"></i></a></li>
                </ul>
            }

            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="page-container">
        <div class="page-content">

            @if (User.Identity.IsAuthenticated)
            {
                @Html.Partial("_Menu")
            }

            <div class="content-wrapper">
                <div class="page-header page-header-default">
                    <div class="breadcrumb-line">
                        <ul class="breadcrumb">
                            <li><a href="@Url.Action("Index", "Home")"><i class="icon-home2 position-left"></i> Home</a></li>
                            @if (ViewBag.breadcrumb != null)
                            {
                                foreach (var i in (List<SelectListItem>)ViewBag.breadcrumb)
                                {
                                    if (i.Value == "active")
                                    {
                                        <li class="active">@i.Text</li>
                                    }
                                    else
                                    {
                                        <li><a href="@i.Value">@i.Text</a></li>
                                    }
                                }
                            }
                        </ul>
                    </div>
                </div>
                <div class="content">

                    @RenderBody()

                    <div class="footer text-muted">
                        © 2020. @VerifikatorPendapatan.Helper.ConfigModel.AppName by <a href="https://www.sanatasystem.net/" target="_blank">Sanata System</a>
                    </div>
                </div>
            </div>

        </div>
    </div>

    @Html.Partial("_Footer")
    @RenderSection("scripts", required: false)
</body>
</html>

VerifikatorPendapatan/Views/Shared/_Menu.cshtml
@using Microsoft.AspNet.Identity
<div class="sidebar sidebar-main">
    <div class="sidebar-content">
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="navigation-header"><span>Menu</span> <i class="icon-menu" title="Menu"></i></li>
                        <li><a href="@Url.Action("Index", "Home")"><i class="icon-home"></i> <span>Home</span></a></li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-cart5"></i> <span>Transaksi</span></a>
                            <ul class="hidden-ul">
                                <li><a href="@Url.Action("Create", "PengakuanPendapatan")">Pengakuan Pendapatan</a></li>
                                <li><a href="@Url.Action("Index", "PengakuanPendapatan")">List Pengakuan Pendapatan</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-paperplane"></i> <span>Posting</span></a>
                            <ul class="hidden-ul">
                                <li><a href="@Url.Action("Index", "PostingKeuangan")">Posting Keuangan</a></li>
                                <li><a href="@Url.Action("Cancel", "PostingKeuangan")">Cancel Posting Keuangan</a></li>
                            </ul>
                        </li>
                        <li><a href="#" onclick="alertpopup('Comming Soon !', 'info');"><i class="icon-gear"></i> <span>Setup Awal</span></a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>