VerifikatorPendapatan/Controllers/PengakuanPendapatanController.cs
using VerifikatorPendapatan.Entities.SIM;
using VerifikatorPendapatan.Helper;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using VerifikatorPendapatan.Models;

namespace VerifikatorPendapatan.Controllers
{
    public class PengakuanPendapatanController : Controller
    {
        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.AU_ListAudit.AsQueryable().Where(x => x.Batal == false);
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y => y.NRM.Contains(x.Value) ||
                                y.NamaPasien.Contains(x.Value) ||
                                y.NRM.Contains(x.Value) ||
                                y.NoInvoice.ToString().Contains(x.Value) ||
                                y.NoBukti.ToString().Contains(x.Value) ||
                                y.TipePasien.ToString().Contains(x.Value) 
                                );

                        if (x.Key == "Tipe" && !string.IsNullOrEmpty(x.Value) && x.Value != "ALL")
                        {
                            proses = proses.Where(y => y.Tipe.Contains(x.Value));
                        }
                        if (x.Key == "TipePasien" && !string.IsNullOrEmpty(x.Value) && x.Value != "ALL")
                        {
                            proses = proses.Where(y => y.TipePasien.Contains(x.Value));
                        }
                        if (x.Key == "Posting" && !string.IsNullOrEmpty(x.Value) && x.Value != "ALL")
                        {
                            var posting = (x.Value == "1") ? true : false;
                            proses = proses.Where(y => y.Posting == posting);
                        }
                    }
                    if (filter[3].Key == "AllPeriode" && filter[3].Value == "false")
                    {
                        if (filter[1].Key == "FromDate")
                        {
                            if (!string.IsNullOrEmpty(filter[1].Value))
                            {
                                var fDate = DateTime.Parse(filter[1].Value).Date; ;
                                proses = proses.Where(y => y.Tanggal >= fDate);
                            }
                        }
                        if (filter[2].Key == "ToDate")
                        {
                            if (!string.IsNullOrEmpty(filter[2].Value))
                            {
                                var tDate = DateTime.Parse(filter[2].Value).Date;
                                proses = proses.Where(y => y.Tanggal <= tDate);
                            }
                        }
                    }

                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        NoBukti = x.NoBukti,
                        Tanggal = x.Tanggal.ToString("dd/MM/yyyy"),
                        Jam = x.Jam.ToString("HH:mm"),
                        TipePasien = x.TipePasien,
                        NoInvoice = x.NoInvoice,
                        NRM = x.NRM,
                        NamaPasien = x.NamaPasien,
                        Posting = x.Posting
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, PengakuanPendapatanModel model)
        {

            try
            {
                using (var s = new SIMEntities())
                {
                    
                    var id = "";
                    var userid = User.Identity.GetUserId();
                    if (_process == "DELETE")
                    {
                        id = model.NoBukti;
                        s.AU_DeleteAudit(id);
                        s.SaveChanges();
                    }

                    //var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                    //{
                    //    Activity = $"SetupVendor-{_process}; id:{id};".ToLower()
                    //};
                    //UserActivity.InsertUserActivity(userActivity);

                    return HConvert.Success();
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Detail(string id)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var m = s.AU_GetHeader.FirstOrDefault(x => x.NoBukti == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    var au = s.AU_ListAudit.FirstOrDefault(x => x.NoBukti == id);
                    var dPendapatan = s.AU_GetDetailPendapatan.Where(x => x.NoBukti == m.NoBukti).OrderByDescending(x => x.Debet).ToList();
                    var dTunai= s.AU_GetDetailTunai.Where(x => x.NoBukti == m.NoBukti).OrderByDescending(x => x.Debet).ToList();
                    var dPiutang = s.AU_GetDetailPiutang.Where(x => x.NoBukti == m.NoBukti).OrderBy(x => x.Akun_Name).ToList();
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            NoBukti = m.NoBukti,
                            Tanggal = m.Tanggal.ToString("dd/MM/yyyy"),
                            Jam = m.Jam.ToString("HH:mm"),
                            TglTransaksi = (m.TglTransaksi == null ? "" : m.TglTransaksi.Value.ToString("dd/MM/yyyy")),
                            NoReg = m.NoReg,
                            TglReg = m.TglReg.Value.ToString("dd/MM/yyyy"),
                            NRM = m.NRM,
                            NamaPasien = m.NamaPasien,
                            JenisKerjasama = m.JenisKerjasama,
                            Nama_Customer = m.Nama_Customer,
                            NoKartu = m.NoKartu,
                            NoInvoice = au.NoInvoice ?? "" ,
                            Batal = au.Batal != true ? 0 : 1,
                            Posting = au.Posting != true ? 0 : 1,
                        },
                        DetailPendapatan = dPendapatan.ConvertAll(x => new
                        {
                            NoBukti = x.NoBukti,
                            NoBuktiJurnal = x.NoBuktiJurnal,
                            AkunNo = x.AkunNo,
                            Akun_Name = x.Akun_Name,
                            Debet = x.Debet,
                            Kredit = x.Kredit,
                            Keterangan = x.Keterangan
                        }),
                        DetailTunai = dTunai.ConvertAll(x => new
                        {
                            NoBukti = x.NoBukti,
                            NoBuktiJurnal = x.NoBuktiJurnal,
                            AkunNo = x.AkunNo,
                            Akun_Name = x.Akun_Name,
                            Debet = x.Debet,
                            Kredit = x.Kredit,
                            Keterangan = x.Keterangan
                        }),
                        DetailPiutang = dPiutang.ConvertAll(x => new
                        {
                            NoBukti = x.NoBukti,
                            NoBuktiTransaksi = x.NoBuktiTransaksi,
                            AkunID = x.AkunID,
                            Akun_Name = x.Akun_Name,
                            NilaiPiutang = x.NilaiPiutang,
                            CustomerID = x.CustomerID,
                            Nama_Customer = x.Nama_Customer,
                            Keterangan = x.Keterangan,
                            
                        })
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public string Proses(string FromDate, string Todate)
        {
           
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        s.Database.CommandTimeout = 180;

                        var d = s.Verifikator_Proses(FromDate, Todate).ToList();

                        dbContextTransaction.Commit();

                        if (d == null)
                        {
                            return JsonConvert.SerializeObject(new
                            {
                                IsSuccess = false,
                                Data = new
                                {

VerifikatorPendapatan/Views/PengakuanPendapatan/Create.cshtml
@using VerifikatorPendapatan.Helper
@{
    ViewBag.Title = "Proses Pengakuan Pendapatan";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
};
}
<style>
    .bar-container {
        background: #f0f0f0;
        height: 10px;
        width: 100%;
        border-radius: 10px;
    }

    .bar {
        background: #00F260; /* fallback for old browsers */
        background: -webkit-linear-gradient(to left, #0575E6, #00F260); /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to left, #0575E6, #00F260); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        height: 10px;
        width: 0%;
        border-radius: 10px;
        transition: width 400ms;
    }
</style>
<form id="formtable" class="form-horizontal">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-flat">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <h5 class="panel-title">Proses Pengakuan Pendapatan</h5>
                    </div>
                </div>
                <div class="panel panel-body">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Dari Tanggal</label>
                        <div class="col-md-4">
                            <input type="date" id="FromDate" name="FromDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                        </div>
                        <label class="col-md-2 control-label">Sampai Tanggal</label>
                        <div class="col-md-4">
                            <input type="date" id="ToDate" name="ToDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                        </div>
                    </div>

                    <div id="loading-bar" class="hidden">
                        <hr />

                        <div class="form-group text-center">
                            <div class="col-md-12">
                                <label id="name_bar" class="text-center">0%</label>
                                <div class="bar-container">
                                    <div class="bar" id="bar"></div>
                                </div>
                                <label id="massage_bar" class="mt-10"></label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 text-right">
                        <button type="button" onclick="opmodal_prosesPengakuanPendapatan()" class="btn bg-primary btn-labeled"><b><i class="icon-sync"></i></b> Proses Pengakuan</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="modal_verfy" class="modal fade">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h6 class="modal-title"> <span class="icon-warning"></span> Verifikator Pendapatan</h6>
            </div>

            <div class="modal-body">
                <p>Apakah anda yakin ingin memproses semua Pengakuan Pendapatan pada tanggal tersebut ?</p>
            </div>

            <div class="modal-footer">
                <button type="button"  data-dismiss="modal" class="btn btn-link">Tidak</button>
                <button type="button" onclick="prosesPengakuanPendapatan()" class="btn bg-primary btn-labeled"><b><i class="icon-sync"></i></b> Proses Pengakuan</button>
            </div>
        </div>
    </div>
</div>

<script>
    function opmodal_prosesPengakuanPendapatan() {
        $('#modal_verfy').modal('show');
        $('#loading-bar').addClass('hidden');
    }

    function prosesPengakuanPendapatan() {
        $('#modal_verfy').modal('hide');
        $('#loading-bar').removeClass('hidden');

        var bar = document.getElementById('bar');
        var namebar = document.getElementById('name_bar');

        namebar.innerHTML = '0%';
        bar.style.width = '0%';

        var count = 0;

        count = count + 10;

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Proses","PengakuanPendapatan")',
            data: {
                FromDate: $('#FromDate').val(),
                ToDate: $('#ToDate').val(),
            },
            beforeSend: function (xhr) {
                count = count + 80;
            },
            success: function (j) {
                var data = JSON.parse(j);
                console.log(data);
                count = count + 10;
                bar.style.width = count + '%';
                namebar.innerHTML = count + '%';
                if (data.IsSuccess) {
                    if (data.Data.CountAll > 0) {
                        $('#massage_bar').html(data.Data.Mssg);
                    } else {
                        $('#massage_bar').html('Data tidak ditemukan');
                    }
                } else {
                    $('#massage_bar').html("Error : <br />" + data.Message);
                }
            }
        })
    };
</script>

VerifikatorPendapatan/Views/PengakuanPendapatan/Index.cshtml
@using VerifikatorPendapatan.Helper
@{
    ViewBag.Title = "PengakuanPendapatan";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
};
}
<style>
    .action-danger:after {
        content: '\e99e';
    }
    .active-info {
        background: #00bcd4 !important;
        color: #fff !important;
    }
</style>
<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">
                Pengakuan Pendapatan
            </h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    @*<li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>*@
                    <li><a class="panel-action action-danger hidden" href="javascript:cancelpengakuanpendapatan()"></a></li>
                    <li><a class="panel-action action-reload" href="javascript:itable.refresh()"></a></li>
                </ul>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header form-horizontal col-md-12 mt-15" style=" border: none; ">
                <label class="control-label col-md-1">Search</label>
                <div class="col-md-3">
                    <input type="search" class="form-control" data-itable-filter="All" data-itable-filter-type="contains" placeholder="Type to filter...">
                </div>
                <label class="control-label col-md-1 col-md-offset-6">Show:</label>
                <div class="col-md-1">
                    <select class="form-control itable-pagesize">
                        <option selected>10</option>
                        <option>25</option>
                        <option>50</option>
                        <option>100</option>
                    </select>
                </div>
            </div>
            <div class="datatable-header form-horizontal col-md-12 mt-10 pb-15">
                <div class="col-md-2">
                    <label>Periode</label>
                    <input type="date" class="form-control input-periode" value="@DateTime.Now.ToString("yyyy-MM-dd")" id="fromdate" data-itable-filter="FromDate" onchange="javascript:itable.refresh()" />
                </div>
                <div class="col-md-2">
                    <label>Sampai</label>
                    <input type="date" class="form-control input-periode" value="@DateTime.Now.ToString("yyyy-MM-dd")" id="todate" data-itable-filter="ToDate" onchange="javascript:itable.refresh()" />
                </div>
                <div class="col-md-1 text-center">
                    <label class="mt-20">
                        All Periode <br />
                        <input type="checkbox" id="allperiode" data-itable-filter="AllPeriode" onchange="javascript:itable.refresh()" />
                    </label>
                </div>
                <div class="col-md-2">
                    <label>Status Posting</label>
                    <select id="posting" data-itable-filter="Posting" onchange="javascript:itable.refresh()">@Html.Raw(HList.Posting)</select>
                </div>
                <div class="col-md-2">
                    <label>Tipe Pasien</label>
                    <select id="tipepasien" data-itable-filter="TipePasien" onchange="javascript:itable.refresh()">@Html.Raw(HList.TipePasien)</select>
                </div>
                <div class="col-md-3">
                    <label>Tipe Transaksi</label>
                    <select id="tipe" data-itable-filter="Tipe" onchange="javascript:itable.refresh()">@Html.Raw(HList.Tipe)</select>
                </div>
            </div>
            <div class="datatable-scroll">
                <table id="tbl_pengakuanpendapatan" class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr>
                            <th class="sorting" data-itable-sorting="NoBukti" style="width:150px;">No Bukti<i></i></th>
                            <th class="sorting" data-itable-sorting="Tanggal">Tanggal<i></i></th>
                            <th class="sorting" data-itable-sorting="Jam">Jam<i></i></th>
                            <th class="sorting" data-itable-sorting="TipePasien">TipePasien<i></i></th>
                            <th class="sorting" data-itable-sorting="NoInvoice">No Invoice<i></i></th>
                            <th class="sorting" data-itable-sorting="NRM">NRM<i></i></th>
                            <th class="sorting" data-itable-sorting="NamaPasien">Nama Pasien<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<div id="deletepengakuanpendapatan" class="modal fade">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
                <h4 class="modal-title">Hapus</h4>
            </div>
            <div class="modal-body">
                <p><span id="countlistselected"></span> Data dipilih, Anda yakin akan menghapus data ini ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="button" class="btn btn-danger" onclick="cancelpengakuanpendapatan_proses()"><i class="icon-trash position-left"></i> Hapus</button>
            </div>
        </div>
    </div>
</div>

<style>
    .bg-posting {
        color: #fff !important;
        background: #81C784 !important;
    }
</style>
<script>
    $('#tipe').select2();
    $('#posting').select2();
    $('#tipepasien').select2();
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'Tanggal',
            orderbytype: false,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="100" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        var bg = (value.Posting == true) ? "bg-posting" : "";
                        tbody += '<tr class="cursor-pointer odd  ' + bg + '" data-nobukti="' + value.NoBukti + '" data-posting="' + value.Posting + '"> ';

                        // column
                        tbody += '<td>' + value.NoBukti + '</td>';
                        tbody += '<td>' + value.Tanggal + '</td>';
                        tbody += '<td>' + value.Jam + '</td>';
                        tbody += '<td>' + value.TipePasien + '</td>';
                        tbody += '<td>' + value.NoInvoice + '</td>';
                        tbody += '<td>' + value.NRM + '</td>';
                        tbody += '<td>' + value.NamaPasien + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        //tbody += '<li><a href="javascript:isetup.opensetup(\'EDIT\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-pencil"></i> Edit</a></li>';
                        tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\',{ id : \'' + value.NoBukti + '\'})"><i class="icon-eye"></i> Detail</a></li>';
                        if (value.Posting == false) {
                            tbody += '<li><a href="javascript:isetup.opensetup(\'DELETE\',{ id : \'' + value.NoBukti + '\'})"><i clasUrlrl="icon-trash"></i> Delete</a></li>';
                        } else {
                        }

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });
        itable.refresh();
    });

    document.addEventListener("DOMContentLoaded", function (event) {
        $('#tbl_pengakuanpendapatan tbody').click('tr',function (e) {
                var j_this = $(e.target).closest('tr');
                var j_tbody = j_this.closest('tbody');
                var hasClass = j_this.hasClass('active-info');
                var posting = $(e.target).closest('tr').data('posting');
                if (posting == true) {
                    hasClass = true;
                    alertpopup("Data sudah diposting", "info");
                }
                if (hasClass) {
                    j_this.removeClass('active-info');
                } else {
                    j_this.addClass('active-info');
            }

            if ($('#tbl_pengakuanpendapatan tbody').find('.active-info').length > 0) {
                $('.action-danger').removeClass('hidden');
            } else {
                $('.action-danger').addClass('hidden');
            }
        });
    });

    function cancelpengakuanpendapatan() {
        var nobukti = [];
        $('#tbl_pengakuanpendapatan tbody').find('.active-info').each(function () {
            nobukti.push({
                NoBukti: $(this).data('nobukti'),
                Delete: true,
            });
        });

        if (nobukti.length == 0) {
            alertpopup("Belum ada data yang dipilih.", "info");
            loading(false);
            return;
        }

        $("#countlistselected").html(nobukti.length);

        $('#deletepengakuanpendapatan').modal('show');
    }

    function cancelpengakuanpendapatan_proses() {
        loading(true);

        var nobukti = [];
        $('#tbl_pengakuanpendapatan tbody').find('.active-info').each(function () {
            nobukti.push({
                NoBukti: $(this).data('nobukti'),
                Delete: true,
            });
        });

        if(nobukti.length == 0) {
            alertpopup("Belum ada data yang dipilih.", "info");
            loading(false);
            return;
        }

        $.ajax({
            url: "@Url.Action("Cancel", "PengakuanPendapatan")",
            type: "POST",
            data: {
                id: nobukti
            },
            dataType: "JSON",
            success: function (r) {
                $('#tbl_pengakuanpendapatan tbody').find('.active-info').removeClass('active-info');

                itable.refresh();
                loading(false);

                $('#deletepengakuanpendapatan').modal('hide');
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);
                loading(false);

                $('#deletepengakuanpendapatan').modal('hide');
            }
        });
    }
</script>
@Html.Partial("Setup")